DROP TABLE IF EXISTS "CATEGORIES";

CREATE TABLE "CATEGORIES" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USERSET"(user_id) ON DELETE CASCADE
);