DROP TABLE IF EXISTS "ITEM_TAGS";

CREATE TABLE "ITEM_TAGS" (
    item_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    PRIMARY KEY (item_id, tag_id),
    FOREIGN KEY (item_id) REFERENCES "ITEM"(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES "TAG"(id) ON DELETE CASCADE
);