DROP TABLE IF EXISTS "ITEMS";

CREATE TABLE "ITEMS" (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NULL,
    user_id INTEGER NOT NULL,
    barcode VARCHAR(255) NULL,
    category_id INTEGER NOT NULL,
    location_id INTEGER NOT NULL,
    photo_id INTEGER NOT NULL,
    receipt_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USERSET"(user_id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES "CATEGORIES"(id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES "LOCATION"(id) ON DELETE CASCADE,
    FOREIGN KEY (photo_id) REFERENCES "PHOTO"(id) ON DELETE CASCADE,
    FOREIGN KEY (receipt_id) REFERENCES "RECEIPT"(id) ON DELETE CASCADE
);
