DROP TABLE IF EXISTS "LOCATIONS";

CREATE TABLE "LOCATIONS" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USERSET"(user_id) ON DELETE CASCADE
);