DROP TABLE IF EXISTS "RECEIPTS";

CREATE TABLE "RECEIPTS" (
    id SERIAL PRIMARY KEY,
    location_purchased VARCHAR(255) NOT NULL,
    was_delivered BOOLEAN NOT NULL,
    receipt_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "USERSET"(user_id) ON DELETE CASCADE
);
