trigger:
  branches:
    include:
    - main
  paths:
    include:
    - inc_files/*.inc  # Trigger when .INC files are added/changed

pool:
  vmImage: 'ubuntu-latest'

variables:
  # If needed, you can define variables here or refer to variable groups
  # varGroup: 'MyVariableGroup'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: pip install psycopg2-binary
  displayName: 'Install PostgreSQL dependencies'

- script: |
    python SQLAutoRunner.py \
      --inc-dir $(System.DefaultWorkingDirectory)/Database/INC \
      --db-host $(PG_HOST) \
      --db-name $(PG_DATABASE) \
      --db-user $(PG_USER) \
      --db-password $(PG_PASSWORD)
  displayName: 'Process SQL scripts'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'SQLAutoRunner.log'
    artifactName: 'logs'
  condition: always()