# azure-pipelines.yml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Database/DEP/*.dep  # Trigger when .INC files are added/changed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    mkdir -p CI/logs
  displayName: 'Create log directory structure'

- script: pip install psycopg2-binary
  displayName: 'Install PostgreSQL dependencies'

- script: |
    python sql_auto_script.py \
      --inc-dir $(System.DefaultWorkingDirectory)/inc_files \
      --db-host $(PG_HOST) \
      --db-name $(PG_DATABASE) \
      --db-user $(PG_USER) \
      --db-password $(PG_PASSWORD)
  displayName: 'Process SQL scripts'
  
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/logs'
    artifactName: 'sql-execution-logs'
  condition: always()